version: "3.7"

services:
  redis:
    image: "redis:6.0-alpine"
    ports:
      - "6379:6379"
    networks:
      - app-tier

  worker:
    build: ./worker/
    networks:
      - app-tier
    depends_on:
      - redis
    command: "celery -A app.celery_config worker -l info"

  beat:
    build: ./worker/
    networks:
      - app-tier
    depends_on:
      - redis
    command: "celery -A app.celery_config beat -l info"

  server:
    build: ./web_server/
    ports:
      - "8000:8000"
    networks:
      - app-tier
    command: >
      /bin/bash -c "
      uvicorn app.main:app --host 0.0.0.0;
      "

networks:
  app-tier:
    driver: bridge